spring:
  data:
    mongodb:
     username: ${MONGO_USER:fsduser}
     password: ${MONGO_PASSWORD:fsduser}
     database: ${MONGO_DATABASE:notedb}
     port: ${MONGO_PORT:27017}
     host: ${MONGO_HOST:localhost}
  application:
    name: note-service
server:
  port: 8082
