spring:
  data:
    mongodb:
 #     authentication-database:
     username: ${MONGO_USER:fsduser}
     password: ${MONGO_PASSWORD:fsduser}
     database: ${MONGO_DATABASE:categorydb}
     port: ${MONGO_PORT:27017}
     host: ${MONGO_HOST:localhost}
  application:
    name: category-service
server:
  port: 8083
   