# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file

version: '3'
services:
 user-auth:
   image: user-auth
   build:
     context: UserAuthentication-Service/
   restart: always
   network_mode: host
   ports:
     - 8080:8080
   depends_on:
     - user-mysql
 user-service:
   image: user-app
   build:
     context: UserService/
   restart: always
   network_mode: host
   ports:
       - 8081:8081
   depends_on:
       - mongo-service
 note-service:
   image: note-app
   build:
     context: NoteService/
   restart: always
   network_mode: host
   ports:
       - 8082:8082
   depends_on:
       - mongo-service
 category-service:
   image: category-app
   build:
     context: CategoryService/
   restart: always
   network_mode: host
   ports:
       - 8083:8093
   depends_on:
       - mongo-service
 reminder-service:
   image: reminder-app
   build:
     context: ReminderService/
   restart: always
   network_mode: host
   ports:
       - 8084:8094
   depends_on:
       - mongo-service
 user-mysql:
   image: mysql:5.6
   restart: always
   network_mode: host
   ports:
     - 3306:3306
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USER: fsduser
     MYSQL_PASSWORD: fsduser
     MYSQL_DATABASE: keepnote
 mongo-service:
     image: mongo:latest
     command: mongod --port 27017
     network_mode: host
     restart: always
     volumes:
       - /data/dump:/data/db
     ports:
       - 27017:27017